In [44]:
# importing necessary libraries
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
import time 
import math

In [45]:
epochs = 100
b = 0
error = 0

In [46]:
class lms():
  def __init__(self):
    np.random.seed(69)
    self.weights = 2 * np.random.random((2,1)) - 1
  
  def train_lms(self, inputs, results, epoch):
   lr_rate = 0.001
   for i in range(epoch):
      output = self.preditct(inputs)
      error = results - output
      n_weight = lr_rate * np.dot(inputs.T, error)
      self.weights += n_weight
      print("Training RMSE: ", np.square(error).mean())
      matched = 0
      if results[i] == output[i]:
        matched += 1
      accuracy = matched / float(len(results)) * 100    
      print("Training Accuracy:", accuracy)
      return output
  
  def activation(self, x):
    a = 1/(1+np.exp(-x))
    a[a >= 0.5] = 1
    a[a < 0.5] = 0
    return a
            
  def preditct(self,inputs):
    np.set_printoptions(suppress = True)
    output = self.activation(np.dot(inputs.astype(float), self.weights))
    return output
    
  def accuracy(self,oglLabel,prediction):
    matched = 0
    for i in range(len(oglLabel)):
      if oglLabel[i] == prediction[i]:
        matched += 1
    accuracy = matched / float(len(oglLabel))      
    return accuracy

In [47]:
dataset = pd.read_csv("Downloads/transfusion.data")

In [48]:
dataset

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2,50,12500,98,1
1,0,13,3250,28,1
2,1,16,4000,35,1
3,2,20,5000,45,1
4,1,24,6000,77,0
...,...,...,...,...,...
743,23,2,500,38,0
744,21,2,500,52,0
745,23,3,750,62,0
746,39,1,250,39,0
747,72,1,250,72,0

In [49]:
xx = (pd.DataFrame(dataset, columns = ['Recency (months)', 'Frequency (times)']).to_numpy())
yy = (pd.DataFrame(dataset, columns = ['whether he/she donated blood in March 2007']).to_numpy())
x_train, x_test, y_train, y_test = train_test_split(xx, yy, shuffle = True, random_state = 33)

In [50]:
t1 = time.time()
print("Training LMS...")
sp1 = lms()
sp1.train_lms(x_train, y_train, epochs)
print("Training Completed")
# print("Training RMSE:", err)
t2 = time.time()

t3 = time.time()
model_prediction = sp1.preditct(x_test)
error_rate = np.square(np.subtract(y_test,model_prediction)).mean()
accuracy = sp1.accuracy(y_test,model_prediction)

Training LMS...
Training RMSE:  0.34402852049910876
Training Accuracy: 0.17825311942959002
Training Completed

In [51]:
print()
print("Testing RMSE :   ",(error_rate))
print("Testing Accuracy :", (accuracy))
t4 = time.time()
print()
print("Training Time: ", (t2-t1))
print("Testing Time :", (t4-t3))
print("Total time :", (t4-t1))

Testing RMSE :    0.23529411764705882
Testing Accuracy : 0.7647058823529411

Training Time:  0.0
Testing Time : 0.01540374755859375
Total time : 0.01540374755859375